#!/usr/bin/env python3
"""Derive a worktree-friendly Serena context from the installed ide-assistant context.

Serena's built-in ``ide-assistant`` context (an alias of ``claude-code``) sets
``single_project: true``. When a project is ALSO pinned at startup via
``--project`` — as this container does with ``--project "$PWD"`` — Serena locks to
that one checkout and STRIPS the ``activate_project`` tool. The trigger, from
Serena's ``agent.py``::

    is_single_project = context.single_project and project is not None

In a git-worktree layout that is the whole problem: an agent whose Serena rooted
at ``main/`` can neither see a worktree's files nor switch to it — the escape
hatch (``activate_project``) has been removed.

This script writes ``~/.serena/contexts/ide-assistant-worktrees.yml``: a
byte-for-byte copy of the upstream context with ONLY ``single_project`` flipped to
false. The result keeps both halves — ``--project "$PWD"`` still auto-roots Serena
at the launch checkout, AND ``activate_project`` stays available so one agent can
switch into any worktree on demand. It runs at image build, so the derived context
always tracks whatever the installed Serena ships (no hand-maintained duplicate to
drift). If a Serena upgrade renames or moves the flag, ``transform`` fails loudly
and the build breaks — better than silently shipping a context that re-locks
worktrees.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# ide-assistant is an alias of the claude-code context; that YAML is the source.
SOURCE_CONTEXT = "claude-code"
DERIVED_NAME = "ide-assistant-worktrees"

# The default install location of serena-agent's uv tool venv.
DEFAULT_TOOL_ROOT = Path.home() / ".local/share/uv/tools/serena-agent"

# `single_project: true` on its own line (tolerating surrounding whitespace).
_SINGLE_PROJECT_RE = re.compile(r"^[ \t]*single_project:[ \t]*true[ \t]*$", re.MULTILINE)

_HEADER = (
    "# GENERATED by plugins/serena/derive_context.py — do not edit by hand.\n"
    f"# A copy of Serena's built-in '{SOURCE_CONTEXT}' (ide-assistant) context with\n"
    "# single_project flipped to false, so `--project` auto-rooting coexists with the\n"
    "# activate_project tool. That combination is what lets one agent reach across git\n"
    "# worktrees. Regenerated at every image build to track the installed Serena.\n"
)


def find_source(tool_root: Path | None = None) -> Path:
    """Locate the ``claude-code.yml`` context shipped inside the installed serena-agent."""
    root = tool_root or DEFAULT_TOOL_ROOT
    pattern = f"**/serena/resources/config/contexts/{SOURCE_CONTEXT}.yml"
    matches = sorted(root.glob(pattern))
    if not matches:
        raise FileNotFoundError(
            f"Could not find {SOURCE_CONTEXT}.yml under {root} (pattern {pattern!r}). "
            "Is serena-agent installed?"
        )
    return matches[0]


def transform(text: str) -> str:
    """Return ``text`` with the ``single_project`` flag flipped from true to false.

    Raises ``ValueError`` unless the source contains exactly one
    ``single_project: true`` line, so a change in Serena's context format breaks the
    build loudly instead of silently producing a context that still locks worktrees.
    """
    matches = _SINGLE_PROJECT_RE.findall(text)
    if len(matches) != 1:
        raise ValueError(
            f"expected exactly one 'single_project: true' line, found {len(matches)}; "
            "Serena's context format may have changed — review before shipping"
        )
    flipped = _SINGLE_PROJECT_RE.sub("single_project: false", text)
    return _HEADER + flipped


def dest_path() -> Path:
    """Where the derived context must live to be resolvable as ``--context ide-assistant-worktrees``."""
    return Path.home() / ".serena" / "contexts" / f"{DERIVED_NAME}.yml"


def main(argv: list[str] | None = None) -> int:
    source = find_source()
    dest = dest_path()
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(transform(source.read_text(encoding="utf-8")), encoding="utf-8")
    print(f"serena: wrote {dest} (derived from {source})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
