#!/usr/bin/env python3
"""Compose each agent's global rules file from the read-only base rules
(/agent-rules/AGENTS.md) plus the AGENTS.md fragments of the plugins ENABLED in
this container.

Why a generated file instead of the old symlink: /agent-rules is a read-only
bind mount (usually an external rules repo), so a plugin's usage guidance cannot
be appended there. up.sh runs this once at `up`; an interactive-shell hook
(src/rules-compose.bashrc) re-runs it, so the base stays as live as the mount —
the fragments themselves are image-fixed (baked under /opt/plugins).

Enabled-only: the image bakes EVERY plugin's fragment, but a container is told
how to use only the plugins its manifest turned on. up.sh writes that list (the
derived PLUGINS var) to the enabled-file, the single source of truth both the
`up`-time and shell-start composes read.

Byte-identical when no enabled plugin ships a fragment: the base is written
through verbatim, so replacing the symlink with this generator is a no-op until
a plugins/<name>/AGENTS.md actually exists.

Stdlib only (matches wire_plugins.py). Writes are atomic (tmp + rename), which
also swaps a pre-existing symlink target for a regular file WITHOUT ever writing
through it into the read-only mount — os.replace re-points the directory entry,
never the link's target.
"""

import argparse
import os
import sys
from pathlib import Path

# Defaults resolve to the paths up.sh and the image establish; the bashrc hook
# invokes this with no arguments and relies on every one of them.
DEFAULT_BASE = "/agent-rules/AGENTS.md"
DEFAULT_PLUGINS_ROOT = "/opt/plugins"
DEFAULT_ENABLED_FILE = "/home/coder/.config/dev-agent/enabled-plugins"

# Per-agent global rules filenames, relative to the exec user's home. Same set
# up.sh used to symlink (skills stays a symlink — a directory, not composed).
TARGET_RELPATHS = (
    ".claude/CLAUDE.md",
    ".codex/AGENTS.md",
    ".gemini/GEMINI.md",
)

FRAGMENT_NAME = "AGENTS.md"
GEN_NOTICE = (
    "<!-- Generated by dev-agent (src/compose_rules.py): base rules + the "
    "AGENTS.md fragments of the plugins enabled in this container. Edit "
    "plugins/<name>/AGENTS.md, not this file. -->"
)
SECTION_HEADING = "# Plugin tools enabled in this container"


def _read_text(path):
    """Read with newline translation OFF so a no-fragment compose round-trips
    the base byte-for-byte (paired with _write_atomic's newline='')."""
    with open(path, encoding="utf-8", newline="") as f:
        return f.read()


def _write_atomic(path, text):
    """tmp + rename in the target's own directory. os.replace is atomic and
    replaces a symlink entry with the regular file (never writes the target)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.parent / (path.name + ".tmp")
    with open(tmp, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    os.replace(tmp, path)


def read_enabled(enabled_file):
    """The enabled-plugin names, whitespace-split. Missing/empty file → [] (a
    container with no plugins, or before up.sh has written it): the compose then
    emits the base verbatim, which is the correct, safe fallback."""
    path = Path(enabled_file)
    if not path.is_file():
        return []
    return path.read_text(encoding="utf-8").split()


def _safe_name(name):
    """A plugin name is a single path segment. up.sh feeds manifest-validated
    names ([A-Za-z0-9_-]), but this module also reads an on-disk enabled-file
    standalone, so reject anything that could escape the plugins root (a '..'
    or a separator) before it reaches a filesystem read — defense in depth."""
    return name and name not in (".", "..") and "/" not in name and "\\" not in name


def load_fragments(plugins_root, names):
    """(name, text) for each enabled plugin that ships a non-empty AGENTS.md,
    in the given order (manifest order — deterministic, author-controllable).
    A plugin without a fragment, or with an empty one, is silently skipped."""
    root = Path(plugins_root)
    fragments = []
    for name in names:
        if not _safe_name(name):
            continue
        frag = root / name / FRAGMENT_NAME
        if not frag.is_file():
            continue
        text = frag.read_text(encoding="utf-8")
        if not text.strip():
            continue
        fragments.append((name, text))
    return fragments


def compose(base_text, fragments):
    """base_text, then a fenced 'enabled tools' section carrying each fragment.
    No fragments → base_text is returned UNCHANGED (byte-identical guarantee)."""
    if not fragments:
        return base_text
    parts = [base_text.rstrip("\n"), "", GEN_NOTICE, SECTION_HEADING, ""]
    for _name, text in fragments:
        parts.append(text.strip("\n"))
        parts.append("")
    return "\n".join(parts).rstrip("\n") + "\n"


def default_targets(home):
    return [Path(home) / rel for rel in TARGET_RELPATHS]


def run(base, plugins_root, enabled_file, targets, announce=False):
    """Compose the file and write every target. Returns 0 on success; a missing
    base is a warn-and-skip (return 1) so the shell hook never clobbers existing
    targets with nothing when the mount is briefly absent."""
    base_path = Path(base)
    if not base_path.is_file():
        print(f"  ⚠ base rules {base_path} not found — leaving agent rules files as-is",
              file=sys.stderr)
        return 1

    base_text = _read_text(base_path)
    names = read_enabled(enabled_file)
    fragments = load_fragments(plugins_root, names)
    composed = compose(base_text, fragments)

    for target in targets:
        _write_atomic(Path(target), composed)

    if announce:
        if fragments:
            print("  ✓ agent rules composed (base + " +
                  ", ".join(n for n, _ in fragments) + ")")
        else:
            print("  ✓ agent rules composed (base only — no enabled plugin ships an AGENTS.md)")
    return 0


def _home():
    """The exec user's real home (passwd), matching wire_plugins._home so a
    future ENV HOME=… in the image can't misdirect the targets."""
    try:
        import pwd
        return Path(pwd.getpwuid(os.getuid()).pw_dir)
    except (ImportError, KeyError):
        return Path(os.environ.get("HOME", "/home/coder"))


def main(argv):
    ap = argparse.ArgumentParser(description="Compose agent rules = base + enabled-plugin fragments.")
    ap.add_argument("--base", default=DEFAULT_BASE)
    ap.add_argument("--plugins-root", default=DEFAULT_PLUGINS_ROOT)
    ap.add_argument("--enabled-file", default=DEFAULT_ENABLED_FILE)
    ap.add_argument("--target", action="append", dest="targets",
                    help="Output file (repeatable). Default: the three agent global files under $HOME.")
    ap.add_argument("--announce", action="store_true", help="Print a ✓ summary line (up.sh uses this; the shell hook does not).")
    args = ap.parse_args(argv)

    targets = args.targets if args.targets else default_targets(_home())
    return run(args.base, args.plugins_root, args.enabled_file, targets, announce=args.announce)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
